[package]
name = "secret-server"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus = "3.14.1"
tokio = { version = "1", features = ["full"] }
oo7 = { path = "../" }
serde = "1.0.193"
once_cell = "1.19.0"
